# Generated by Django 4.2.5 on 2023-10-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzapp', '0003_product_image_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_product',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
